[package]
name = "kb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "2"
sysinfo = "0.29.7"
itertools = "0.11"
fontdue = "0.7.3"
chrono = "0.4.26"
image = "0.24"
